### ISSUE TITLE
Are we still waiting for a new npm release?

### ISSUE THREAD

**Issue by rdmurphy** [vercel/git-hooks#9]
Hello!

I saw that a couple new versions were prepared here in the repo to [grab the Node +12 compatibility](https://github.com/vercel/git-hooks/commit/8479611491492433bcd085b387c1f60a81949e10), but I don't think they've made it all the way out to `npm` yet. Are there any updates on that effort?

Thank you! 🙏

**Comment by Qix-** [comment]
Yes, my access was revoked, I'm still waiting on a decision to be made there. Not much I can do until then, unfortunately.

**Comment by leerob** [comment]
I'll be releasing this package shortly!

**Comment by leerob** [comment]
https://github.com/vercel/git-hooks/releases/tag/1.0.0
